### ISSUE TITLE
1.18.2 Crash on startup with java.lang.RuntimeException

### ISSUE THREAD

**Issue by RMEngelbrecht** [ejektaflex/Bountiful-Fabric#36]
Hey, I'm sorry for creating an issue about 1.18.2 but I haven't been able to get the mod to work at all.

I'm using Bountiful 2.0.2 for Fabric
Fabric API 0.67.0
Fabric Language Kotlin 1.8.6+kotlin1.7.21
and Kambrik 3.1.0

No other mods are installed, and I've tried a variety of combinations of the dependencies to see if any of them would fix the issue (due to possible changes made in later versions). None of this has made it work sadly, which is why I'm posting this here. Hoping it isn't just me being stupid and wasting your time.

I've attached the crash log down below,

[crash-2022-11-23_22.28.34-client.txt](https://github.com/ejektaflex/Bountiful-Fabric/files/10079289/crash-2022-11-23_22.28.34-client.txt)

**Comment by ejektaflex** [comment]
Oh boy - this is luckily an easy fix. The important part of the error is the end:
```
Caused by: java.lang.NoSuchMethodError: 'net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings.breakByHand(boolean)'
	at io.ejekta.bountiful.content.board.BoardBlock.<init>(BoardBlock.kt:29)
	at io.ejekta.bountiful.content.BountifulContent.<clinit>(BountifulContent.kt:35)
	at io.ejekta.bountiful.config.BountifulIO.<clinit>(BountifulIO.kt:48)
	at io.ejekta.bountiful.Bountiful.<init>(Bountiful.kt:28)
```
Fabric API I believe made changes to `FabricBlockSettings` in 0.67.0, removing it completely. Not sure why they did that when plenty of people are still going to use it for their 1.18.2 games. 

Try roll back to an earlier version of Fabric API before 0.67.0 and see if that helps. 
Thank you!

**Comment by ejektaflex** [comment]
Actually, I've tracked down the real issue. They never removed `FabricBlockSettings` - rather, they removed that method in a new version of Fabric Api for 1.18.2. Bountiful on Fabric doesn't work with Minecraft 1.18.2, and is not marked compatible with 1.18.2. It's my mistake to mark that version of the mod as loadable on 1.18.2 even though it should not be - but as shown on CurseForge, it's only officially compatible with 1.18 and 1.18.1.

Sorry about that!

**Comment by RMEngelbrecht** [comment]
Ah that makes so much more sense! Thanks for replying so quickly!
